# Generated by Django 5.2.4 on 2025-07-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='region',
        ),
        migrations.AddField(
            model_name='slide',
            name='summary',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
